language: node_js 

services:
  - postgresql
install: 
  - npm install
  - npm install -g @vue/cli @vue/cli-service-global
script:
  - npm run serve

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master