language: node_js 

services:
  - postgresql

install:
  - npm ci

script:
  - npm install
  - npm run serve

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master