language: node_js
node_js:
  - "node"

services:
  - postgresql

cache: npm

script: 
  - npm run build
before_script:
  - npx sequelize-cli db:create
  - npx sequelize-cli db:migrate

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master
