language: node_js
node_js:
  - "node"

services:
  - postgresql

cache:
  directories:
    - node_modules

script: 
  - npm run build

after_succes:
  - cd serve
  - npm install pm2
  - pm2 start api.js
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master
