language: node_js
node_js:
 - "node"

cache: npm

script: 
  - cd serve
  - npm install --save-dev sequelize-cli
  - sequelize db:create
  - sequelize db:migrate
  - sequelize db:seed:all
  - npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master
