language: node_js
node_js:
  - "node"

services:
  - postgresql

cache: npm

script: 
  - npm run build
  - npm run test

before_script:
  - cd serve
  - npx sequelize-cli db:create
  - npx sequelize-cli db:migrate
  - npx sequelize-cli db:seed:all


deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master
