language: node_js
node_js:
  - "node"

services:
  - postgresql

cache:
  directories:
    - node_modules

script: 
  - npm run build

after_succes:
  - cd serve
  - npx sequelize-cli db:migrate
  - npx sequelize-cli db:seed:all
  - npm start
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master
