language: node_js
node_js:
 - "node"

cache: npm

script: 
  - npm run build
before_script:
  - psql -c 'create database tasklist' -U postgres
  - npx sequelize-cli db:migrate

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master
